version: "3.8"

services:
  postgres:
    image: postgres:15.2
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=smart_host
    restart: always

volumes:
  postgres-data:
